import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
const inter = Work_Sans({ subsets: ["latin"] });
import SessionWrapper from "@/components/SessionWrapper";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
